config/routes.rb
MouseTracker::Application.routes.draw do
  
  root "users#new"

  get 'site/:id/interactions' => "sites#site_interactions", as: :site_interactions
  resources :sites
  resources :auths
  resources :interactions
  get 'interactions/site/:id' => "interactions#combined_interactions_site", as: :combined_interactions_site
  resources :users
  get 'users/:id/scripts' => "users#scripts", as: :scripts

end

app/models/interaction.rb
class Interaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :site
end

private

# coords_string = "287,507;287,507;298,386;303,335;306,312;308,298;"

def parse_coords(coords)
  parsedCoords=[]
  coords_array = coords.split(";")

  coords_array.each do |pointStr|
    pointArr = pointStr.split(",")
    parsedCoords << {x: pointArr[0].to_i, y: pointArr[1].to_i }
  end
  return parsedCoords.to_json
end

def combine_coords(coords)
  combined_coords = ""
  coords.each do |coord|
    combined_coords += coord.move
  end
  return parse_coords(combined_coords)
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :interactions
  has_many :users, through: :interactions
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :interactions
  has_many :sites, through: :interactions

  attr_accessor :password

  def authenticated? pwd
      self.hashed_password ==
        BCrypt::Engine.hash_secret(pwd, self.salt)
  end

  before_save :hash_the_password
  private 

  def hash_the_password
    unless self.password == nil
      self.salt = BCrypt::Engine.generate_salt
      self.hashed_password = BCrypt::Engine.hash_secret self.password, self.salt
      self.password = nil
    end 
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end 
  end 

end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  def new
    if current_user
      redirect_to sites_path
      flash[:notice] = "you are logged alreday logged in. Logout to create a new account"
    else
      @user = User.new
    end
  end

  def create
    if !(User.where(email: params[:user][:email]).empty?)
      user = User.find_by(email: params[:user][:email])
      if user.authenticated?(params[:user][:password])
        session[:user_id] = user.id
        redirect_to sites_path
        flash[:notice] = "You are logged in"
      else
        redirect_to new_auth_path
        flash[:error] = "email and password did not match"
      end
    else
      redirect_to new_auth_path
      flash[:error] = "We couldn't find that email. Try again or create an account."   
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_auth_path
  end
end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController

  skip_before_filter :verify_authenticity_token
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  def cors_preflight_check
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
    headers['Access-Control-Max-Age'] = '1728000'
  end

  def new
    @interaction = Interaction.new
  end

  def create
    # binding.pry
    site = Site.find_or_create_by(url: params["interaction"]["url"])
    @interaction = Interaction.new(int_params)
    @interaction.site_id = site.id
    # if an interaction already exists with the same :time param, then update its :move param
    if Interaction.where(time: @interaction.time, user_id: @interaction.user_id)[0]
      old_interaction = Interaction.where(site_id: @interaction.site_id ,time: @interaction.time, user_id: @interaction.user_id)[0]
      old_interaction.move = @interaction.move
      old_interaction.save!
      redirect_to interactions_path
    else
      if @interaction.save
        redirect_to interactions_path
      else
        redirect_to interaction_path
      end
    end
  end

  def show
    @interaction = Interaction.find(params[:id])
    @coordsArray = parse_coords(@interaction.move)
    @url = Site.find(@interaction.site_id).url
  end

  def combined_interactions_site
    site = Site.find(params[:id]) 
    @interaction = site.interactions.first
    @combined_coords = combine_coords(site.interactions)
    @url = site.url
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def index
    @interactions = Interaction.all
  end

  private 

  def int_params
    params.require(:interaction).permit(:move, :time, :user_id, :window_width, :body_height)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
    @sites = User.find(current_user.id).sites.uniq
  end

  def site_interactions
    @site = Site.find(params[:id])
    @site_interactions = Interaction.where(user_id: current_user.id, site_id: params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if current_user
      redirect_to sites_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if User.find_by(email: @user.email)
      redirect_to new_user_path
      flash[:error] = "sorry that email already is associated with an account"
    else  
      if @user.save
        session[:user_id] = @user.id
        redirect_to scripts_path(current_user.id)
      else
        redirect_to new_user_path
        flash[:error] = "aww shucks, user was not created!"
      end
    end  
  end

  def index
    @users = User.all
  end

  private 

  def user_params
    params.require(:user).permit(:email, :password, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auths/create.html.erb
<h1>Auths#create</h1>
<p>Find me in app/views/auths/create.html.erb</p>

app/views/auths/destroy.html.erb
<h1>Auths#destroy</h1>
<p>Find me in app/views/auths/destroy.html.erb</p>

app/views/auths/new.html.erb
<body class="heatMapImg">
  
  <div class="row-fluid">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h1><span class="titleMouse">Mouse</span> <span class="titleMapper">Mapper</span> Login</h1>
    </div>
    <div class="col-md-3"></div>
  </div>
  <div class="row-fluid">
    <div class="col-md-4"></div>
    <div class="col-md-4" >
      <%= form_for @user, {url:"/auths", method:"post"} do |u| %>
        <div class="form-group">
          <%= u.label :email %>
          <%= u.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= u.label :password %>
          <%= u.password_field :password, class: "form-control" %>
        </div>
        <%= u.submit "Log in", class: "btn signUpBtn pull-right" %>
      <% end %>
    </div>
    <div class="col-md-4"></div>
  </div>

</body>

app/views/interactions/combined_interactions_site.html.erb
<script type="text/javascript">

window.onload = function() {
  //create iframe
  $("body").append("<iframe src=<%= @url %> style='width:<%= @interaction.window_width %>px;height:<%= @interaction.body_height %>px'</iframe>");
  
  var windowLength = String(window.innerWidth -25)+"px";
  var bodyHeight = String(document.body.scrollHeight)+"px";
  document.body.innerHTML += "<div id='heatMapContainer' style='z-index:-1;height:1000px;border:2px solid black;position:absolute;top:4px;left:4px'></div>";
  document.getElementById('heatMapContainer').style.width = windowLength;
  document.getElementById('heatMapContainer').style.height = bodyHeight;


  var coordsArray = <%= raw @combined_coords %>
  var cleanData = [];

  // adds a populates the cleanData array with coordinates that have a count attribute. This allows use to pass the cleanData array to the heatmapper
  function cleanCoordArrayRuby() {
    for(var i=0; i<coordsArray.length; i++) {
      var obj = coordsArray[i];
      if(matchFound(obj) === false){
        var countObj = obj;
        countObj.count = 1;
        cleanData.push(countObj);
      }
    }
    console.log(cleanData);
    displayMap();
  }

  function matchFound(obj) {
    if (cleanData.length === 0) {
      return false;
    }
    else {
      for (var i=0; i<cleanData.length; i++) {
        var cleanObj = cleanData[i];
        if (obj.x === cleanObj.x && obj.y === cleanObj.y) {
          cleanObj.count += 1;
          return true;
        }
      }
      return false;
    }
  }

  function displayMap() {
    console.log("displayMap is fired");
    var config = {
      "radius": 50,
      "element": document.getElementById("heatMapContainer"),
      "visible": true,
      "opacity": 100,
      "gradient": { 0.45: "rgb(0,0,255)", 0.55: "rgb(0,255,255)", 0.65: "rgb(0,255,0)", 0.95: "yellow", 1.0: "rgb(255,0,0)" }
    };
    var heatmap = heatmapFactory.create(config);
    heatmap.store.setDataSet({ max: 10, data: cleanData } );
    //change z-index inorder to make the heatMap the first layer
    document.getElementById("heatMapContainer").style.zIndex="1";
  }

  cleanCoordArrayRuby(coordsArray);

};


</script>

app/views/interactions/index.html.erb
<% @interactions.each do |int| %>
  <%= int.move %>
  <%= int.time %> 
<% end %> 

app/views/interactions/new.html.erb
<h1>Interactions#new</h1>
<p>Find me in app/views/interactions/new.html.erb</p>

app/views/interactions/show.html.erb
<script type="text/javascript">

window.onload = function() {
  //create iframe
  $("body").append("<iframe src=<%= @url %> style='width:<%= @interaction.window_width %>px;height:<%= @interaction.body_height %>px'</iframe>");
  
  var windowLength = String(window.innerWidth -25)+"px";
  var bodyHeight = String(document.body.scrollHeight)+"px";
  document.body.innerHTML += "<div id='heatMapContainer' style='z-index:-1;height:1000px;border:2px solid black;position:absolute;top:4px;left:4px'></div>";
  document.getElementById('heatMapContainer').style.width = windowLength;
  document.getElementById('heatMapContainer').style.height = bodyHeight;


  var coordsArray = <%= raw @coordsArray %>
  var cleanData = [];

  // adds a populates the cleanData array with coordinates that have a count attribute. This allows use to pass the cleanData array to the heatmapper
  function cleanCoordArrayRuby() {
    for(var i=0; i<coordsArray.length; i++) {
      var obj = coordsArray[i];
      if(matchFound(obj) === false){
        var countObj = obj;
        countObj.count = 1;
        cleanData.push(countObj);
      }
    }
    console.log(cleanData);
    displayMap();
  }

  function matchFound(obj) {
    if (cleanData.length === 0) {
      return false;
    }
    else {
      for (var i=0; i<cleanData.length; i++) {
        var cleanObj = cleanData[i];
        if (obj.x === cleanObj.x && obj.y === cleanObj.y) {
          cleanObj.count += 1;
          return true;
        }
      }
      return false;
    }
  }

  function displayMap() {
    console.log("displayMap is fired");
    var config = {
      "radius": 50,
      "element": document.getElementById("heatMapContainer"),
      "visible": true,
      "opacity": 100,
      "gradient": { 0.45: "rgb(0,0,255)", 0.55: "rgb(0,255,255)", 0.65: "rgb(0,255,0)", 0.95: "yellow", 1.0: "rgb(255,0,0)" }
    };
    var heatmap = heatmapFactory.create(config);
    heatmap.store.setDataSet({ max: 10, data: cleanData } );
    //change z-index inorder to make the heatMap the first layer
    document.getElementById("heatMapContainer").style.zIndex="1";
  }

  cleanCoordArrayRuby(coordsArray);

};

</script>
  

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img class="mouseIcon" src="http://mousemapper.herokuapp.com/assets/mouse.svg"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="navbarGreeting">Hi <%= current_user.name %></li>
        <% else %>
            <% if params[:controller] == "auths" %>
              <li><%= link_to "Sign up", new_user_path, class: "btn logIn" %></li>
            <% else %>   
              <li><%= link_to "Log In", new_auth_path, class: "btn logIn" %></li>
            <% end %>
        <% end %>
        <% if current_user %> 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Options<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% if controller_name != "sites" %>
                <li><%= link_to "Sites", sites_path %></li>
              <% else %>
                <li><%= link_to "Scripts", scripts_path(current_user.id) %></li>
              <% end %>  
              <li class="divider"></li>
              <li><%= link_to "Log out", new_auth_path, {method: "delete"} %></li>
            </ul>
          </li>
        <% end %> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MouseTracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,800,400' rel='stylesheet' type='text/css'>
 
  <%= csrf_meta_tags %>
</head>
<body>
<% if controller_name != "interactions" %>  
  <%= render "layouts/navbar" %>
<% end %>   
<%= flash[:notice] %> 
<%= flash[:error] %> 
<%= yield %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

<%#= params %> 
<%#= controller_name %> 

</body>
</html>

app/views/sites/index.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h1>Sites Your Tracking</h1>
  </div>
  <div class="col-md-2">
</div>  
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="tableShell">
      <table class="table table-striped">
        <th>#</th>
        <th>URL</th>
        <th># of Visits</th>
        <% if @sites %>
          <% @sites.each_with_index do |site, index| %>
            <tr>
              <td><%= index %></td>
              <td><%= site.url %></td>
              <td><%= link_to Interaction.where(user_id: current_user.id, site_id: site.id).length, site_interactions_path(site.id) %></td>
            </tr>
          <% end %>
        <% else %> 
          <h2>No Sites have been tracked yet</h2>     
        <% end %>   
      </table>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/sites/site_interactions.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h1>Site Visits</h1>
  </div>
  <div class="col-md-2">
</div> 
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="tableShell">
      <h4><%= @site.url %></h4>
      <table class="table table-striped">
        <th>Time</th>
        <tr>
          <td><%= link_to "All", combined_interactions_site_path(@site.id) %> </td>
        </tr>
        <% @site_interactions.each do |si| %> 
          <tr>
            <td><%= link_to si.time, interaction_path(si.id) %></td>
          </tr>
        <% end %>   
      </table>
    </div>
  </div>  
  <div class="col-md-4"></div>
</div>    

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>User Index</h1>

<% @users.each do |user| %> 
  <%= user.hashed_password %> 
  <%= user.email %>
  <br>
<% end %> 

app/views/users/new.html.erb
<body class="heatMapImg">
  
  <div class="row-fluid">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h1>Welcome to <span class="titleMouse">Mouse</span> <span class="titleMapper">Mapper</span></h1>
    </div>
    <div class="col-md-3"></div>
  </div>
  <div class="row-fluid">
    <div class="col-md-4"></div>
    <div class="col-md-4" >
      <%= form_for @user do |u| %>
        <div class="form-group">
          <%= u.label :name %>
          <%= u.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= u.label :email %>
          <%= u.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= u.label :password %>
          <%= u.password_field :password, class: "form-control" %>
        </div>
        <%= u.submit "Sign Up", class: "btn signUpBtn pull-right" %>
      <% end %>
    </div>
    <div class="col-md-4"></div>
  </div>

  <p class="mouseAttribution">Mouse by Nina Sandgaard Rasmussen</p>

</body>

app/views/users/scripts.html.erb
<div class="row-fluid">
  <div class="col-md-6">
    <h1>Drag to Bookmarks Bar</h1>
    <div class="bookmarklet"><a class="bookmarkletLink" href="javascript:javascript: (function () {
      var bookmarklet = document.createElement('script'); 
      bookmarklet.setAttribute('src', 'http://mousemapper.herokuapp.com/javascripts/bookmarklet.js');
      document.body.appendChild(bookmarklet); 
      var mapLib = document.createElement('script'); 
      mapLib.setAttribute('src', 'http://mousemapper.herokuapp.com/assets/heatmap.js');
      document.body.appendChild(mapLib);
      var jQueryLib = document.createElement('script'); 
      jQueryLib.setAttribute('src', 'http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js');
      document.body.appendChild(jQueryLib);
      mouseTrackerUserId = <%= current_user.id %>;
    }());;"><span class="bookmarkletLinkExpansion"></span>Get Data</a>
      <img class="fireIcon" src="http://mousemapper.herokuapp.com/assets/fire.svg">
    </div>
  </div>
  <div class="col-md-6">
    <h1>Copy Script</h1>
    <div>
      <pre>

        &lt;script type='text/javascript'&gt; window.mouseTrackerUserId = <%= current_user.id %> &lt;/script&gt;

        &lt;script type='text/javascript' src='http://mousemapper.herokuapp.com/javascripts/copyScripts.js'&gt; &lt;/script&gt;

        &lt;script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js'&gt; &lt;/script&gt;
        
      </pre>
    </div>
  </div>  
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>